--
-- TODO: Run configs for executing SQL
--

-- KIM perm and roles

insert into KRIM_PERM_T (PERM_ID, NMSPC_CD, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, OBJ_ID, VER_NBR)
  values ('KRATRN-CTXT_PERM', 'KRA-TRNG', 52, 'Maintain KRMS Agenda', 'View and maintain Agendas in the KRA-TRNG namespace', 'Y', UUID(), 1)
;

insert into KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, ROLE_ID, PERM_ID)
  values ('KRATRN-KRMS-1', uuid(), 'KRATRN-ADMN_ROLE', 'KRATRN-CTXT_PERM')
;

INSERT INTO KRIM_ROLE_T(ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT)
  VALUES ('KRATRN-NCAA-ROLE', uuid(), 1, 'Althetics Dept Approvers','KRA-TRNG','Approver for the athletics department','1','Y', now())
;

INSERT INTO KRIM_ROLE_T(ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, DESC_TXT, KIM_TYP_ID, ACTV_IND, LAST_UPDT_DT)
  VALUES ('KRATRN-INTL-ROLE', uuid(), 1, 'International Office Approvers','KRA-TRNG','Approver for the International Office','1','Y', now())
;

INSERT INTO KRIM_ROLE_MBR_T(ROLE_MBR_ID, VER_NBR, OBJ_ID, ROLE_ID, MBR_ID, MBR_TYP_CD)
VALUES('KRTRN-NCAA-ROLE-MBR-1', 1, UUID(), 'KRATRN-NCAA-ROLE', 'earl', 'P')
;

INSERT INTO KRIM_ROLE_MBR_T(ROLE_MBR_ID, VER_NBR, OBJ_ID, ROLE_ID, MBR_ID, MBR_TYP_CD)
VALUES('KRTRN-INTL-ROLE-MBR-1', 1, UUID(), 'KRATRN-INTL-ROLE', 'erin', 'P')
;


-- PeopleFlows

INSERT INTO KREW_PPL_FLW_T (PPL_FLW_ID, ACTV, NM, NMSPC_CD)
  VALUES ('KRATRN-INTL-PPF', 'Y', 'International Office Approvers', 'KRA-TRNG')
;

INSERT INTO KREW_PPL_FLW_MBR_T (PPL_FLW_MBR_ID, PPL_FLW_ID, ACTN_RQST_PLCY_CD, MBR_TYP_CD, MBR_ID, PRIO, RSP_ID)
  VALUES ('KRATRN-INTL-PPF-MBR-1', 'KRATRN-INTL-PPF', 'F', 'R', 'KRATRN-INTL-ROLE', 1, 'KRATRN-INTL-PPF-RSP-1')
;


--
-- KRMS stuff
--

--  Context

insert into KRMS_CNTXT_T (CNTXT_ID, NMSPC_CD, NM, DESC_TXT)
values ('KRATRN-1-CNTXT', 'KRA-TRNG', 'StudentApplication', 'Context for Student Application rules')
;

insert into KRMS_CNTXT_VLD_ACTN_TYP_T (CNTXT_VLD_ACTN_ID, CNTXT_ID, ACTN_TYP_ID)
values ('KRATRN-KRMS-1', 'KRATRN-1-CNTXT', '1001')
;


-- student country of origin

insert into KRMS_TERM_SPEC_T (TERM_SPEC_ID, NM, TYP, DESC_TXT, NMSPC_CD, VER_NBR)
  values ('KRATRN-KRMS-CTRY-TERM-SPEC', 'studentCountryCode', 'java.lang.String', 'Student Applicant Country of Origin', 'KRA-TRNG', 1)
;

insert into KRMS_TERM_T (TERM_ID, TERM_SPEC_ID, DESC_TXT, VER_NBR)
  values ('KRATRN-KRMS-CTRY-TERM', 'KRATRN-KRMS-CTRY-TERM-SPEC', 'Student Applicant Country of Origin', 1)
;

insert into KRMS_CNTXT_VLD_TERM_SPEC_T (CNTXT_TERM_SPEC_PREREQ_ID, CNTXT_ID, TERM_SPEC_ID, PREREQ)
  values ('KRATRN-KRMS-VLD-CTRY-TERM', 'KRATRN-1-CNTXT', 'KRATRN-KRMS-CTRY-TERM-SPEC', null)
;

insert into KRMS_TYP_T (TYP_ID, NM, NMSPC_CD, SRVC_NM)
  values ('KRATRN-KRMS-CTRY-RSLVR-TYP', 'studentCountryCodeTermResolver', 'KRA-TRNG', 'studentCountryCodeTermResolver')
;

insert into KRMS_TERM_RSLVR_T (TERM_RSLVR_ID, NMSPC_CD, NM, TYP_ID, OUTPUT_TERM_SPEC_ID)
  values ('KRATRN-KRMS-CTRY-RSLVR', 'KRA-TRNG', 'studentCountryCodeTermResolver', 'KRATRN-KRMS-CTRY-RSLVR-TYP', 'KRATRN-KRMS-CTRY-TERM-SPEC');
;


-- Student Application agenda

INSERT INTO KRMS_AGENDA_T (AGENDA_ID, CNTXT_ID, NM)
  VALUES ('KRATRN-KRMS-APPL-AGENDA', 'KRATRN-1-CNTXT', 'Student Application')
;

INSERT INTO KRMS_PROP_T (PROP_ID, DESC_TXT, DSCRM_TYP_CD, RULE_ID)
  VALUES ('KRATRN-KRMS-INTL-PROP', 'International Student', 'S', 'KRATRN-KRMS-INTL-RULE')
;

INSERT INTO KRMS_RULE_T (RULE_ID, NM, NMSPC_CD, PROP_ID)
  VALUES ('KRATRN-KRMS-INTL-RULE', 'International Student', 'KRA-TRNG', 'KRATRN-KRMS-INTL-PROP')
;


-- actions and attrs

INSERT INTO KRMS_ACTN_T (ACTN_ID, NM, NMSPC_CD, SEQ_NO, TYP_ID, RULE_ID)
  VALUES ('KRATRN-KRMS-INTL-ACTN', 'Route to International Dept Approvers', 'KRA-TRNG', 1, '1001', 'KRATRN-KRMS-INTL-RULE')
;

INSERT INTO KRMS_ACTN_ATTR_T (ACTN_ATTR_DATA_ID, ATTR_VAL, ACTN_ID, ATTR_DEFN_ID)
  VALUES ('KRATRN-KRMS-INTL-ACTN-ATTR-1', 'International Office Approvers', 'KRATRN-KRMS-INTL-ACTN', '1006')
;

INSERT INTO KRMS_ACTN_ATTR_T (ACTN_ATTR_DATA_ID, ATTR_VAL, ACTN_ID, ATTR_DEFN_ID)
  VALUES ('KRATRN-KRMS-INTL-ACTN-ATTR-2', 'KRATRN-INTL-PPF', 'KRATRN-KRMS-INTL-ACTN', '1000')
;


-- agenda items

INSERT INTO KRMS_AGENDA_ITM_T (AGENDA_ITM_ID, AGENDA_ID, RULE_ID)
  VALUES ('KRATRN-KRMS-INTL-AGENDA-ITEM', 'KRATRN-KRMS-APPL-AGENDA', 'KRATRN-KRMS-INTL-RULE')
;

UPDATE KRMS_AGENDA_T SET INIT_AGENDA_ITM_ID = 'KRATRN-KRMS-INTL-AGENDA-ITEM'
  WHERE (AGENDA_ID = 'KRATRN-KRMS-APPL-AGENDA')
;


-- proposition params

INSERT INTO KRMS_PROP_PARM_T (PROP_PARM_ID, PARM_TYP_CD, SEQ_NO, PARM_VAL, PROP_ID)
  VALUES ('KRATRN-KRMS-INTL-PROP-PARM-1', 'T', 0, 'KRATRN-KRMS-CTRY-TERM', 'KRATRN-KRMS-INTL-PROP')
;

INSERT INTO KRMS_PROP_PARM_T (PROP_PARM_ID, PARM_TYP_CD, SEQ_NO, PARM_VAL, PROP_ID)
  VALUES ('KRATRN-KRMS-INTL-PROP-PARM-2', 'C', 1, 'USA', 'KRATRN-KRMS-INTL-PROP')
;

INSERT INTO KRMS_PROP_PARM_T (PROP_PARM_ID, PARM_TYP_CD, SEQ_NO, PARM_VAL, PROP_ID)
  VALUES ('KRATRN-KRMS-INTL-PROP-PARM-3', 'O', 2, '!=', 'KRATRN-KRMS-INTL-PROP')
;
